In [1]:
import pandas as pd

In [5]:
import numpy as np

percentages = [20 40 10 20 100]

LR- Logistic Regression DT Decision Tree RF Random Forest NN Neural Network

ML zoomcamp introduction to Numpy

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [14]:
a = np. array ([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [16]:
a[2] = 10

In [19]:
a

array([ 1,  2, 10,  5,  7, 12])

In [24]:
np.arange (3, 10)

array([3, 4, 5, 6, 7, 8, 9])